/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.angularjs.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Users service. Represents a row in the &quot;rivetlogic_angular_Users&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rivetlogic.angularjs.model.impl.UsersModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rivetlogic.angularjs.model.impl.UsersImpl}.
 * </p>
 *
 * @author charles.rodriguez
 * @see Users
 * @see com.rivetlogic.angularjs.model.impl.UsersImpl
 * @see com.rivetlogic.angularjs.model.impl.UsersModelImpl
 * @generated
 */
public interface UsersModel extends BaseModel<Users> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a users model instance should use the {@link Users} interface instead.
	 */

	/**
	 * Returns the primary key of this users.
	 *
	 * @return the primary key of this users
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this users.
	 *
	 * @param primaryKey the primary key of this users
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the user name of this users.
	 *
	 * @return the user name of this users
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this users.
	 *
	 * @param userName the user name of this users
	 */
	public void setUserName(String userName);

	/**
	 * Returns the email of this users.
	 *
	 * @return the email of this users
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this users.
	 *
	 * @param email the email of this users
	 */
	public void setEmail(String email);

	/**
	 * Returns the full name of this users.
	 *
	 * @return the full name of this users
	 */
	@AutoEscape
	public String getFullName();

	/**
	 * Sets the full name of this users.
	 *
	 * @param fullName the full name of this users
	 */
	public void setFullName(String fullName);

	/**
	 * Returns the company of this users.
	 *
	 * @return the company of this users
	 */
	@AutoEscape
	public String getCompany();

	/**
	 * Sets the company of this users.
	 *
	 * @param company the company of this users
	 */
	public void setCompany(String company);

	/**
	 * Returns the position of this users.
	 *
	 * @return the position of this users
	 */
	@AutoEscape
	public String getPosition();

	/**
	 * Sets the position of this users.
	 *
	 * @param position the position of this users
	 */
	public void setPosition(String position);

	/**
	 * Returns the password of this users.
	 *
	 * @return the password of this users
	 */
	@AutoEscape
	public String getPassword();

	/**
	 * Sets the password of this users.
	 *
	 * @param password the password of this users
	 */
	public void setPassword(String password);

	/**
	 * Returns the age of this users.
	 *
	 * @return the age of this users
	 */
	public int getAge();

	/**
	 * Sets the age of this users.
	 *
	 * @param age the age of this users
	 */
	public void setAge(int age);

	/**
	 * Returns the state of this users.
	 *
	 * @return the state of this users
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this users.
	 *
	 * @param state the state of this users
	 */
	public void setState(String state);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Users users);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Users> toCacheModel();

	@Override
	public Users toEscapedModel();

	@Override
	public Users toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}